
import { Event } from './types';

export const MOCK_EVENTS: Event[] = [
  {
    id: 1,
    title: 'Global Beats Music Festival',
    date: 'November 21-23, 2025',
    location: 'Harmony Park, Metro City',
    description: 'A three-day celebration of music from around the world, featuring international artists and diverse genres.',
    longDescription: 'Immerse yourself in a vibrant atmosphere at the Global Beats Music Festival. Experience an eclectic mix of sounds, from Latin jazz to African drumming, and from indie rock to electronic dance music. The festival grounds will also host artisan markets, gourmet food trucks, and interactive art installations. A truly unforgettable weekend for music lovers of all ages.',
    imageUrl: 'https://picsum.photos/seed/music/600/400',
    category: 'Music',
    organizer: 'World Harmony Productions',
    ticketPrice: 75.00,
  },
  {
    id: 2,
    title: 'Renaissance Art Exhibition',
    date: 'November 15 - December 20, 2025',
    location: 'Grand Museum of Art',
    description: 'Explore the masterpieces of the Renaissance, featuring works by Leonardo da Vinci, Michelangelo, and Raphael.',
    longDescription: 'Step back in time and witness the genius of the Renaissance masters. This curated exhibition brings together iconic paintings and sculptures from the 14th to the 16th centuries. Audio guides narrated by renowned art historians will provide deep insights into the cultural and historical context of each piece. Special workshops on fresco painting will be available on weekends.',
    imageUrl: 'https://picsum.photos/seed/art/600/400',
    category: 'Art',
    organizer: 'The Art Heritage Foundation',
    ticketPrice: 25.00,
  },
  {
    id: 3,
    title: 'A Midsummer Night\'s Dream',
    date: 'December 5-15, 2025 (Fri-Sun)',
    location: 'Starlight Outdoor Theatre',
    description: 'Shakespeare\'s classic comedy brought to life under the stars in a magical, immersive theatrical experience.',
    longDescription: 'Enter an enchanted forest where fairies, lovers, and amateur actors collide in Shakespeare\'s most beloved comedy. The Starlight Outdoor Theatre provides the perfect backdrop for this whimsical tale of love and magic. Bring a picnic and enjoy a captivating evening of professional theatre in a breathtaking natural setting.',
    imageUrl: 'https://picsum.photos/seed/theatre/600/400',
    category: 'Theatre',
    organizer: 'Starlight Players',
    ticketPrice: 40.00,
  },
  {
    id: 4,
    title: 'International Food & Wine Fair',
    date: 'November 29-30, 2025',
    location: 'City Convention Center',
    description: 'Savor flavors from every corner of the globe, with celebrity chef demonstrations and wine tasting sessions.',
    longDescription: 'Embark on a culinary journey at the International Food & Wine Fair. Sample authentic dishes from over 30 countries, attend live cooking shows hosted by world-famous chefs, and refine your palate at our exclusive wine and cheese pairing workshops. A paradise for foodies and a great day out for the whole family.',
    imageUrl: 'https://picsum.photos/seed/food/600/400',
    category: 'Food & Drink',
    organizer: 'Gourmet Ventures Inc.',
    ticketPrice: 50.00,
  },
   {
    id: 5,
    title: 'Luminous Lantern Festival',
    date: 'December 19-21, 2025',
    location: 'Botanical Gardens',
    description: 'A dazzling display of handcrafted lanterns, cultural performances, and traditional crafts to celebrate the harvest moon.',
    longDescription: 'As dusk falls, the Botanical Gardens transform into a magical wonderland illuminated by thousands of intricate lanterns. The Luminous Lantern Festival is a family-friendly event that features live music, traditional dance performances, shadow puppetry, and a bustling night market with delicious street food and unique crafts. It\'s a beautiful celebration of light, art, and community.',
    imageUrl: 'https://picsum.photos/seed/lantern/600/400',
    category: 'Festival',
    organizer: 'Cultural Connections',
    ticketPrice: 20.00,
  },
   {
    id: 6,
    title: 'Contemporary Dance Showcase',
    date: 'December 6, 2025',
    location: 'The Modern Stage',
    description: 'Experience the power and passion of contemporary dance with performances by groundbreaking choreographers.',
    longDescription: 'Pushing the boundaries of movement and expression, the Contemporary Dance Showcase presents a compelling program of new works from emerging and established artists. This evening of dance explores themes of identity, technology, and the human condition through breathtaking athleticism and raw emotion. A post-show Q&A with the choreographers offers a unique glimpse into their creative process.',
    imageUrl: 'https://picsum.photos/seed/dance/600/400',
    category: 'Dance',
    organizer: 'Velocity Dance Collective',
    ticketPrice: 35.00,
  }
];
